id: P005607
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20172
  title: མཐོ་སྒང་གི་ནོར་ནག
  author: ''
  volumes:
    1b0d821a80fb425d9195d76b549ba9f5:
      image_group_id: I1KG23336
      title: ''
      volume_number: 1
      total_pages: 104
      base_file: v001.txt
